version: '3.8'
services:
  mysql:
    extends:
      file: docker/compose.mysql.yml
      service: mysql

  redis:
    extends:
      file: docker/compose.redis.yml
      service: redis

  kafka:
    extends:
      file: docker/compose.kafka.yml
      service: kafka

  kafka-ui:
    extends:
      file: docker/compose.kafka-ui.yml
      service: kafka-ui

networks:
  default:
    driver: bridge