version: '3.8'
services:
  mysql:
    extends:
      file: docker/compose.mysql.yml
      service: mysql

  redis:
    extends:
      file: docker/compose.redis.yml
      service: redis

  kafka:
    extends:
      file: docker/compose.kafka.yml
      service: kafka

  kafka-ui:
    extends:
      file: docker/compose.kafka-ui.yml
      service: kafka-ui

  loki:
    extends:
      file: docker/compose.monitoring.yml
      service: loki

  grafana:
    extends:
      file: docker/compose.monitoring.yml
      service: grafana

  promtail:
    extends:
      file: docker/compose.monitoring.yml
      service: promtail

  influxdb:
    extends:
      file: docker/compose.monitoring.yml
      service: influxdb

networks:
  default:
    driver: bridge

volumes:
  promtail-positions: {}
  loki-data: {}
  loki-wal: {}
  influx-data: {}