package kr.hhplus.be.server.controller.validation

import jakarta.validation.ConstraintValidator
import jakarta.validation.ConstraintValidatorContext

class AutoGeneratedIdValidator : ConstraintValidator<ValidAutoGeneratedId, Long> {
    override fun isValid(value: Long?, context: ConstraintValidatorContext): Boolean {
        return value != null && value >= 1
    }
}
