package kr.hhplus.be.server.controller.validation
//
//import ValidAutoGeneratedId
//
//@Target(AnnotationTarget.FIELD, AnnotationTarget.VALUE_PARAMETER)
//@Retention(AnnotationRetention.RUNTIME)
//@ValidAutoGeneratedId  // ⭐ 핵심: 메타 애노테이션으로 붙임
//annotation class ValidCouponId(
//    val message: String = "유효하지 않은 쿠폰 ID입니다."
//)
//
//@Target(AnnotationTarget.FIELD, AnnotationTarget.VALUE_PARAMETER)
//@Retention(AnnotationRetention.RUNTIME)
//@ValidAutoGeneratedId
//annotation class ValidUserId(
//    val message: String = "유효하지 않은 유저 ID입니다."
//)
//
