services:
  mysql:
    image: mysql:8.0
    ports:
      - "23306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ${COMPOSE_PROJECT_DIR}/data/mysql/:/var/lib/mysql

