{
 "title": "k6 Simple (InfluxQL)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "VU (Active virtual users)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"vus\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "RPS (Requests/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "SELECT derivative(sum(\"value\"), 1s) FROM \"http_reqs\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Errors/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT derivative(sum(\"value\"), 1s) FROM \"http_req_failed\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Checks/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "SELECT derivative(sum(\"value\"), 1s) FROM \"checks\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "http_req_duration p95 (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "SELECT percentile(\"value\",95) FROM \"http_req_duration\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}